"""foursquare unique

Revision ID: 6fcd8b60df5a
Revises: 9335b2580b47
Create Date: 2019-07-21 19:13:21.989640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6fcd8b60df5a'
down_revision = '9335b2580b47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'venues', ['foursquare_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venues', type_='unique')
    # ### end Alembic commands ###
