"""Add foursquare schema

Revision ID: 9335b2580b47
Revises: 218403f80e25
Create Date: 2019-07-20 21:10:54.856434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9335b2580b47'
down_revision = '218403f80e25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('venue_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'reviews', 'venues', ['venue_id'], ['id'])
    op.add_column('venues', sa.Column('foursquare_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'foursquare_id')
    op.drop_constraint(None, 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'venue_id')
    # ### end Alembic commands ###
